name: build

on: [push]
# on:
#   push:
#     paths:
#     - '**.js'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js 10.x
      uses: actions/setup-node@v1
      with:
        node-version: 10.x
    - name: Start Contract
      run: |
        sudo apt install g++-7 git -y
        git clone https://github.com/synergatika/loyalty-contracts.git
        cd loyalty-contracts
        export CXX="g++-7"
        npm install -g npm@latest
        npm install -g ganache-cli truffle
        npm install 
        npx ganache-cli -l 100000000 -m "candy maple cake sugar pudding cream honey rich smooth crumble sweet treat" > /dev/null &
        truffle migrate
        cd ..
    - run: npm run test
      env:
        CI: true
        APP: dev
        PORT: 3000
        API_URL: http://localhost:3000/
        APP_URL: http://localhost:4200/
        DB_DIALECT: mongo
        DB_HOST: localhost
        DB_PORT: 27017
        DB_NAME: synergy
        DB_USER:
        DB_PASSWORD:
        JWT_SECRET: ${{ secrets.JWT_SECRET }}
        JWT_EXPIRATION: 36000
        TOKEN_LENGTH: 32
        TOKEN_EXPIRATION: 5
        EMAIL_HOST: ${{ secrets.EMAIL_HOST }}
        EMAIL_PORT: ${{ secrets.EMAIL_PORT }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        EMAIL_FROM: Synergy | A Social and Solidarity Economy Toolkit
        ETH_API_ACCOUNT_PRIVKEY: 0xc87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
        ETH_REMOTE_API: localhost
        ETH_CONTRACTS_PATH: contracts
    - name: Publish to Registry
      uses: elgohr/Publish-Docker-Github-Action@master
      with:
        registry: docker.pkg.github.com
        name: synergatika/synergy-api/synergy-api
        username: synergatika
        password: ${{ secrets.GITHUB_TOKEN }}
        cache: true
